typescript
ShiiRochi/wavesurfer-react pull request #34
Opened 2022-01-18 16:31 UTC by shreyas-jadhav

2022-01-18 17:40 UTC, ShiiRochi commented
@shreyas-jadhav, thanks for your help. I'll check asap.

2022-01-23 22:38 UTC, ShiiRochi commented
@shreyas-jadhav, do you have some WIP or can I consider, that it's ready?

2022-01-24 03:10 UTC, shreyas-jadhav commented
Hey, I don't have any WIP for now. You can check it out.

2022-02-01 09:22 UTC, ShiiRochi requested changes
1. tgz file should be removed and added to the ignored list
2. version of the package shouldn't be changed manually

2022-02-01 09:22 UTC, ShiiRochi commented on package.json
> +  "version": "2.0.13",
Version should not be changed, it is controlled with npm cli

2022-02-25 20:13 UTC, ShiiRochi requested changes
Drop commits that removes and adds tarball file and do the same stuff with commits related to version in `package.json`. I don't want to store that information within repository and git history. You can do that stuff with creating dev branch from current master and cherry picking all commits until those with tarball and version updates. If they are commited all together (i.e. with changes) then do soft reset to current (in my repo) master state make hard force push.

2022-02-25 21:22 UTC, ShiiRochi commented
@shreyas-jadhav, I closed this PR because I've already done what I wrote here some time ago. I cherry-picked only required stuff from your repo branches and you can see that Git saved all credits properly, i.e. the contribution of yours is seen, otherwise I would have waited until your response.

2022-02-25 21:22 UTC, closed without merging